objects/Account.object
<CustomObject>
    <fields>
        <fullName>Commision_Percentage__c</fullName>
        <label>Commision Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Agent__c.object
<CustomObject>
    <description>Stores the informations of the users who can access the system.</description>
    <label>Agent</label>
    <nameField>
        <displayFormat>A - {0000}</displayFormat>
        <label>Agent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Agent__c</fullName>
        <label>Agent</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commision_Amount__c</fullName>
        <label>Commision Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DMLclass14.cls
public class DMLclass14 {
    public static void myMethod(){
        Savepoint sp1 = Database.setSavepoint();		//Saving the state of the database
        
        try{
            Opportunity o = [Select Name, Account.ID, Amount, OwnerID from Opportunity where Name like 'Sell Lubri%' LIMIT 1];
            
            Decimal commission = o.Amount * 0.20;		//Calculating the commission of the agent
            
            o.amount = o.amount + commission;			//Updating the amount of Opportunity
            
            update o;		//1 st Database Operation, Updating the Opportuntiy record in Database
            
            
            Commission__c c = new Commission__c();
            c.Commision_Amount__c = commission;
            c.Agent__c = o.ownerId;
            
            insert c;		//2nd Database Operation
            
            Account acc2 = [Select Name from Account where id = :o.accountID];
            
            acc2.Commision_Percentage__c = 20;
            
            update acc2;		//3 rd Database Operation
        }
        catch(Exception e){
            Database.rollback(sp1);
        }
    }
}