objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>RegistrationId__c</fullName>
        <label>RegistrationId</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Total_Expense__c</fullName>
        <label>Total Expense</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Car</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>CarId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Car_Accessory__c.object
<CustomObject>
    <fields>
        <fullName>CarId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Car Accessories</relationshipLabel>
        <relationshipName>Car_Accessories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Car_Accessory_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Car Accessory Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Car Accessory</label>
    <nameField>
        <label>Car Accessory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Car_Service__c.object
<CustomObject>
    <fields>
        <fullName>CarId__c</fullName>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Car Services</relationshipLabel>
        <relationshipName>Car_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Car_Service_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Car Service Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Car Service</label>
    <nameField>
        <label>Car Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CarServiceTriggerHandlerTest.cls
@isTest
public class CarServiceTriggerHandlerTest {
    @testSetup
    private static void testSetup(){
        List<Car__c> carsList = new List<Car__c>();
        List<Car_Service__c> carServiceList = new List<Car_Service__c>();
        List<Car_Accessory__c> carAccessoryList = new List<Car_Accessory__c>();
        
        for(Integer i = 0; i < 5; i++){
            Car__c car = new Car__c();
            car.RegistrationId__c = 'RJ 31 CB ' + i;
           	carsList.add(car);
        }
        
        if(!carsList.isEmpty()){
            insert carsList;
        }
        
        
        for(Car__c car : carsList){
            for(Integer i = 0; i < 2; i++){
                Car_Service__c carService = new Car_Service__c();
                carService.CarId__c = car.Id;
                carService.Name = 'Test ' + i;
                carService.Car_Service_Amount__c = 50;
                carServiceList.add(carService);
            }
            for(Integer i = 0; i < 2; i++){
                Car_Accessory__c carAccessory = new Car_Accessory__c();
                carAccessory.CarId__c = car.Id;
                carAccessory.Name = 'Test ' + i;
                carAccessory.Car_Accessory_Amount__c = 50;
                carAccessoryList.add(carAccessory);
            }
        }
        
        if(!carServiceList.isEmpty()){
            insert carServiceList;
        }
        if(!carAccessoryList.isEmpty()){
            insert carAccessoryList;
        }
    }
    
	@isTest
    private static void afterInsertTest(){        
        
        List<Car__c> carsList  = [SELECT Id, Total_Expense__c FROM Car__c LIMIT 1];
        
        System.assertEquals(200, carsList[0].Total_Expense__c);
        
    }
    
    @isTest
    private static void afterUpdateTest(){
        
        List<Car__c> carAndServiceList = [SELECT Id, (SELECT Id FROM Car_Services__r) FROM Car__c];
        List<Car_Service__c> carServiceList = new List<Car_Service__c>();
        
        for(Car__c car : carAndServiceList){
            for(Car_Service__c carService : car.car_Services__r){
                Car_Service__c cs = new Car_Service__c();
                cs.Id = carService.Id;
                cs.Car_Service_Amount__c = 20;
                carServiceList.add(cs);
            }
        }
        
        Test.startTest();
        update carServiceList;
        Test.stopTest();
        
        List<Car__c> carsList  = [SELECT Id, Total_Expense__c FROM Car__c LIMIT 1];
        
        System.assertEquals(140, carsList[0].Total_Expense__c);
    }
   
    @isTest
    private static void afterDeleteTest(){
        List<Car_Service__c> carServiceList = [SELECT Id, Name FROM Car_Service__c WHERE Name = 'Test 1'];
        
        Test.startTest();
        delete carServiceList;
        Test.stopTest();
        
        List<Car__c> carsList  = [SELECT Id, Total_Expense__c FROM Car__c LIMIT 1];
        
        System.assertEquals(150, carsList[0].Total_Expense__c);
    }
}