objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>CarId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Car_Accessory__c.object
<CustomObject>
    <fields>
        <fullName>CarId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Car Accessories</relationshipLabel>
        <relationshipName>Car_Accessories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Car Accessory</label>
    <nameField>
        <label>Car Accessory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CarAccessoryTriggerHandler.cls
public class CarAccessoryTriggerHandler{
    public static void afterInsert(List<Car_Accessory__c> carAccessoryList){
        Set<Id> carsIds = new Set<Id>();
        List<Car__c> carListToBeUpdated = new List<Car__c>();
        
        for(Car_Accessory__c carAccessory : carAccessoryList){
            if(carAccessory.CarId__c != null){
                carsIds.add(carAccessory.CarId__c);
            }
        }
        
        carListToBeUpdated = CarServiceTriggerHandler.calculateTotalAmount(carsIds);
        
        if(!carListToBeUpdated.isEmpty()){
            update carListToBeUpdated;
        }
    }
    
    public static void afterUpdate(List<Car_Accessory__c> carAccessoryList, Map<Id,Car_Accessory__c> oldMap){
        Set<Id> carsIds = new Set<Id>();
        List<Car__c> carListToBeUpdated = new List<Car__c>();
        
        for(Car_Accessory__c carAccessory : carAccessoryList){
            if(carAccessory.CarId__c != null && oldMap != null){
                carsIds.add(carAccessory.CarId__c);
            }
        }
        
        carListToBeUpdated = CarServiceTriggerHandler.calculateTotalAmount(carsIds);
        
        if(!carListToBeUpdated.isEmpty()){
            update carListToBeUpdated;
        }

    }
    
    public static void afterDelete(List<Car_Accessory__c> oldList){
        Set<Id> carsIds = new Set<Id>();
        List<Car__c> carListToBeUpdated = new List<Car__c>();
        
        for(Car_Accessory__c carAccessory : oldList){
            if(carAccessory.CarId__c != null){
                carsIds.add(carAccessory.CarId__c);
            }
        }
        
        carListToBeUpdated = CarServiceTriggerHandler.calculateTotalAmount(carsIds);
        
        if(!carListToBeUpdated.isEmpty()){
            update carListToBeUpdated;
        }

    }
}