objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Talks</fullName>
                </value>
                <value>
                    <fullName>Deal</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Car</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>CarId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Car_Accessory__c.object
<CustomObject>
    <fields>
        <fullName>CarId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Car Accessories</relationshipLabel>
        <relationshipName>Car_Accessories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Car Accessory</label>
    <nameField>
        <label>Car Accessory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Car_Service__c.object
<CustomObject>
    <fields>
        <fullName>CarId__c</fullName>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Car Services</relationshipLabel>
        <relationshipName>Car_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Car Service</label>
    <nameField>
        <label>Car Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/StatusProcessor.cls
public class StatusProcessor implements Database.Batchable<sObject>,Database.stateful{
    public integer totalServiceRecord = 0;
    public integer totalAccessoryRecord = 0;
    public Database.QueryLocator start(Database.BatchableContext bc){ 
        return Database.getQueryLocator([SELECT Id, Status__c FROM Car__c WHERE Status__c = 'Sold']);
    }
    
    public void execute(Database.BatchableContext bc, List<Car__c> carsList){
        Map<Id,Car__c> carIdToCarMap = new Map<Id,Car__c>(carsList);
        List<Car_Service__c> carServiceListToBeUpdated = new List<Car_Service__c>();
        List<Car_Accessory__c> carAccessoryListToBeUpdated = new List<Car_Accessory__c>();
        
        for(Car_Service__c carService : [SELECT Id, Status__c FROM Car_Service__c WHERE CarId__c IN : carIdToCarMap.keySet() AND Status__c = null]){
            Car_Service__c cs = new Car_Service__c();
            cs.Id = carService.Id;
            cs.Status__c = 'Sold';
            carServiceListToBeUpdated.add(cs);
        }
        
        for(Car_Accessory__c carAccessory : [SELECT Id, Status__c FROM Car_Accessory__c WHERE CarId__c IN : carIdToCarMap.keySet() AND Status__c = null]){
            Car_Accessory__c ca = new Car_Accessory__c();
            ca.Id = carAccessory.Id;
            ca.Status__c = 'Sold';
            carAccessoryListToBeUpdated.add(ca);
        }
        
        totalServiceRecord += carServiceListToBeUpdated.size();
        totalAccessoryRecord += carAccessoryListToBeUpdated.size();
        
        if(!carServiceListToBeUpdated.isEmpty()){
            update carServiceListToBeUpdated;
        }
        
        if(!carAccessoryListToBeUpdated.isEmpty()){
            update carAccessoryListToBeUpdated;
        }     
    }
    
    public void finish(Database.BatchableContext bc){
        System.debug('Total Records Processed : ' + totalServiceRecord);
        System.debug('Total Records Processed : ' + totalAccessoryRecord);
    }
}