objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Total_Expense__c</fullName>
        <label>Total Expense</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Car</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>CarId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Car_Accessory__c.object
<CustomObject>
    <fields>
        <fullName>CarId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Car Accessories</relationshipLabel>
        <relationshipName>Car_Accessories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Car_Accessory_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Car Accessory Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Car Accessory</label>
    <nameField>
        <label>Car Accessory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Car_Service__c.object
<CustomObject>
    <fields>
        <fullName>CarId__c</fullName>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Car Services</relationshipLabel>
        <relationshipName>Car_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Car_Service_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Car Service Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Car Service</label>
    <nameField>
        <label>Car Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CarServiceTriggerHandler.cls
public class CarServiceTriggerHandler {
    public static void afterInsert(List<Car_Service__c> carServiceList){
        Set<Id> carsIds = new Set<Id>();
        List<Car__c> carListToBeUpdated = new List<Car__c>();
        
        for(Car_Service__c carService : carServiceList){
            if(carService.CarId__c != null){
                carsIds.add(carService.CarId__c);
            }
        }
        
        carListToBeUpdated = calculateTotalAmount(carsIds);
        
        if(!carListToBeUpdated.isEmpty()){
            update carListToBeUpdated;
        }
    }
    
    public static void  afterUpdate(List<Car_Service__c> carServiceList, Map<Id,Car_Service__c> oldMap){
         Set<Id> carsIds = new Set<Id>();
        List<Car__c> carListToBeUpdated = new List<Car__c>();
        
        for(Car_Service__c carService : carServiceList){
            if(carService.CarId__c != null && oldMap != null){
                carsIds.add(carService.CarId__c);
            }
        }
        
        carListToBeUpdated = calculateTotalAmount(carsIds);
        
        if(!carListToBeUpdated.isEmpty()){
            update carListToBeUpdated;
        }
    }
    
    public static void afterDelete(List<Car_Service__c> oldList){
         Set<Id> carsIds = new Set<Id>();
        List<Car__c> carListToBeUpdated = new List<Car__c>();
        
        for(Car_Service__c carService : oldList){
            if(carService.CarId__c != null){
                carsIds.add(carService.CarId__c);
            }
        }
        
        carListToBeUpdated = calculateTotalAmount(carsIds);
        
        if(!carListToBeUpdated.isEmpty()){
            update carListToBeUpdated;
        }
    }
    
    public static List<Car__c> calculateTotalAmount(Set<Id> carsIds){
        List<Car__c> carListToBeUpdated = new List<Car__c>();
        Map<Id,Decimal> carIdToTotalServiceAmountMap = new Map<Id,Decimal>();
        Map<Id,Decimal> carIdToTotalAccessoryAmountMap = new Map<Id,Decimal>();
        Map<Id,Car__c> carIdToCarMap;
        
        carIdToCarMap = new Map<Id,Car__c>([SELECT Id, Total_Expense__c FROM Car__c WHERE Id IN : carsIds]);
        
        for(Car_Service__c cs : [SELECT Id, CarId__c, Car_Service_Amount__c FROM Car_Service__c WHERE CarId__c IN : carsIds]){
            Decimal total = 0;
            if(carIdToTotalServiceAmountMap.containsKey(cs.CarId__c)){
                total = carIdToTotalServiceAmountMap.get(cs.CarId__c);
            }
            if(cs.Car_Service_Amount__c != null){
            	total = total + cs.Car_Service_Amount__c;    
            }
            carIdToTotalServiceAmountMap.put(cs.CarId__c, total);
        }
        
        for(Car_Accessory__c ca : [SELECT Id, CarId__c, Car_Accessory_Amount__c FROM Car_Accessory__c WHERE CarId__c IN : carsIds]){
            Decimal total = 0;
            if(carIdToTotalAccessoryAmountMap.containsKey(ca.CarId__c)){
                total = carIdToTotalAccessoryAmountMap.get(ca.CarId__c);
            }
            if(ca.Car_Accessory_Amount__c != null){
            	total = total + ca.Car_Accessory_Amount__c;    
            }
            carIdToTotalAccessoryAmountMap.put(ca.CarId__c, total);
        }
        
        if(carIdToTotalServiceAmountMap != null || carIdToTotalAccessoryAmountMap != null){
            for(Id carId : carIdToTotalServiceAmountMap.keySet()){
                Car__c car = new Car__c();
                car.Id = carId;
                car.Total_Expense__c = carIdToTotalServiceAmountMap.get(carId);
                if(carIdToTotalAccessoryAmountMap.get(carId) != null){
                    car.Total_Expense__c = carIdToTotalServiceAmountMap.get(carId) + carIdToTotalAccessoryAmountMap.get(carId);
                }
                carListToBeUpdated.add(car);
            }
        }
        
        return carListToBeUpdated;
    }
}