objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>RegistrationId__c</fullName>
        <label>RegistrationId</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Talks</fullName>
                </value>
                <value>
                    <fullName>Deal</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Car</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>CarId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Car_Accessory__c.object
<CustomObject>
    <fields>
        <fullName>CarId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Car Accessories</relationshipLabel>
        <relationshipName>Car_Accessories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Car Accessory</label>
    <nameField>
        <label>Car Accessory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Car_Service__c.object
<CustomObject>
    <fields>
        <fullName>CarId__c</fullName>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Car Services</relationshipLabel>
        <relationshipName>Car_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Car Service</label>
    <nameField>
        <label>Car Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/StatusProcessorTest.cls
@isTest
public class StatusProcessorTest {
	@isTest
    private static void testStatusProcessorClass(){
        List<Car__c> carsList = new List<Car__c>();
        List<Car_Service__c> carServiceList = new List<Car_Service__c>();
        List<Car_Accessory__c> carAccessoryList = new List<Car_Accessory__c>();
        
        for(Integer i = 0; i < 100; i++){
            Car__c car = new Car__c();
            car.RegistrationId__c = 'RJ 31 CB ' + i;
            car.Status__c = 'Sold';
            carsList.add(car);
        }
        
        insert carsList;
        
        for(Car__c car : carsList){
                Car_Service__c carService = new Car_Service__c();
                carService.CarId__c = car.Id;
                carServiceList.add(carService);
                
                Car_Accessory__c carAccessory = new Car_Accessory__c();
                carAccessory.CarId__c = car.Id;
                carAccessoryList.add(carAccessory);
        }
        
        Test.startTest();
        insert carServiceList;
        insert carAccessoryList;
        StatusProcessor statusJob = new StatusProcessor();
        Id batchId = Database.executeBatch(statusJob);
        Test.stopTest();
        
        List<Car_Service__c> carServiceListUpdated = [SELECT Id FROM Car_Service__c WHERE Status__c = 'Sold'];
        List<Car_Accessory__c> carAccessoryListUpdated = [SELECT Id FROM Car_Accessory__c WHERE Status__c = 'Sold'];
        
        System.assertEquals(100, carServiceListUpdated.size());
        System.assertEquals(100, carAccessoryListUpdated.size());
    }
}