objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Languages__c</fullName>
        <label>Languages</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/student__c.object
<CustomObject>
    <fields>
        <fullName>Student_Name__c</fullName>
        <inlineHelpText>Enter your name here</inlineHelpText>
        <label>Student Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>student</label>
    <nameField>
        <displayFormat>St  - {0000}</displayFormat>
        <label>student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/sObjectClass1.cls
public class sObjectClass1 
{
    public static void myMethod()
    {
        //*************STANDARD OBJECTS ********************8
        //Create an Account sObject
        
        Account a1 = new Account();
        
        //Create an Contact sObject
        
        Contact c1 = new Contact();
        
        //***********Setting fields in sObject
        
        //Through Constructor
        
        Account a2 = new Account(name = 'Himanshu',NumberOfEmployees = 3000);
        Contact c2 = new Contact(firstname = 'Hrithik',lastname = 'Choudhary',Languages__c = 'Spanish');
        
        //Through Dot Notation
        
        a2.name = 'Namit';
        a2.NumberOfEmployees = 3000;
        
        c2.FirstName = 'Sanyam';
        c2.LastName = 'Garg';
        c2.Languages__c = 'Hindi';
        
        //***************** CUSTOM OBJECTS*****************
        
        Student__c st1 = new Student__c(Student_name__c = 'Himanshu');
        
        //********* GENERIC OBJECTS*****************
        
        sObject s1 = new Account(name = 'Sanyam',NumberOfEmployees = 2000);
        
        sObject s2 = new Contact(Title = 'Aayush');
        
        sObject s3 = new Student__c(Student_Name__c = 'Hrithik');
        
        //***********TWIST WITH GENERIC SOBJECTS *****************8
        //Setting a field in sObject
        
        s1.put('Name','Sahil');
        s3.put('Student_name__c' , 'Himanshu');
        
        //**************** Accessing field value of sObjects
        
        s1.get('name');
        s2.get('name');
        s3.get('Student_name__c');
        
        Integer i1 = (integer)s1.get('NumberOfEmployees');
        System.debug(i1);
    }
}