objects/Rating__c.object
<CustomObject>
    <fields>
        <fullName>Rating_for__c</fullName>
        <label>Rating for</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rating_given_to_which_Student__c</fullName>
        <label>Rating given to which Student</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>student__c.Course_Opted__c</field>
                <operation>equals</operation>
                <value>Salesforce Admin, Salesforce Developer\, Python</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>student__c</referenceTo>
        <relationshipLabel>Ratings</relationshipLabel>
        <relationshipName>Ratings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rating_out_of_10__c</fullName>
        <label>Rating out of 10</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>Rating_given_to_which_Student__r.Student_Name__c</formula>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <label>Rating</label>
    <nameField>
        <displayFormat>R - {0000}</displayFormat>
        <label>Rating ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/student__c.object
<CustomObject>
    <fields>
        <fullName>Student_Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Enter your Email here</inlineHelpText>
        <label>Student Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <inlineHelpText>Enter your name here</inlineHelpText>
        <label>Student Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>student</label>
    <nameField>
        <displayFormat>St  - {0000}</displayFormat>
        <label>student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SOQLClass5.cls
public class SOQLClass5 
{
	public static void myMethod()
    {
        //Relationship Queries
        //
        //****************Child to ParentStud
        //
        //Standard Object
        
        List<Contact> conList = [Select firstName, lastName, Account.Name, Account.NumberOfEmployees from Contact];
        
        //Here Account is the parent Object's reference which is relationship field's name on child object
        
        
        //Custom Object
        
        List<Rating__c> ratList = [Select name, Rating_For__c, Rating_Out_Of_10__c, Rating_given_to_which_Student__r.Name, Rating_given_to_which_Student__r.Student_Email__c from Rating__c];
        
        //Here Rating_given_to_which_Student__r is the parent object's reference which is relationship field's name on child object + __r
        
        
        
        
        
        
        
        
        
        
        //Parent to Child
        //
        //****************** Standard Object
        
        List<Account> accList = [Select name, NumberOfEmployees, (Select lastName, Phone from Contacts) from Account];
        
        //Here Contacts is the child relationship name
        //&&
        //(Select lastName, Phone from Contact) is a subquery / inner query
        
        
        
        
        //Custom Object
        
        List<Student__c> stList = [Select name, Student_Email__c, Student_Name__c, (Select Name, Rating_For__c, Rating_Out_Of_10__c from Ratings__r) from Student__c];
        
        
        
    }
}